# Generated by Django 3.2 on 2024-03-16 10:29

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ("checkout", "0002_remove_orderlineitem_product_size"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
